language: php

php:
  - 7.0
  - 7.1
  - 7.2
  - nightly

cache:
  directories:
    - vendor

install:
  - phpenv config-rm xdebug.ini || true
  - composer config --global discard-changes true
  - composer update
  - composer require satooshi/php-coveralls dev-master --dev
  - composer show --installed

script:
  - find -name "*.php" -not -path "./vendor/*" -print0 | xargs -n 1 -0 php -l
  - phpdbg -qrr vendor/bin/phpunit --coverage-text --coverage-clover build/logs/clover.xml
  - php vendor/bin/php-cs-fixer --diff --dry-run -v fix

after_script:
  - php vendor/bin/coveralls -v
