language: php

php:
  - 7.0
  - 7.1
  - 7.2
  - nightly

cache:
  directories:
    - vendor

install:
  - phpenv config-rm xdebug.ini || true
  - composer install

script:
  - find -name "*.php" -not -path "./vendor/*" -print0 | xargs -n 1 -0 php -l
  - phpdbg -qrr vendor/bin/phpunit --coverage-text --coverage-clover build/logs/clover.xml
  - PHP_CS_FIXER_IGNORE_ENV=1 php vendor/bin/php-cs-fixer --diff --dry-run -v fix

after_script:
  - curl -OL https://github.com/php-coveralls/php-coveralls/releases/download/v1.0.0/coveralls.phar
  - chmod +x coveralls.phar
  - ./coveralls.phar -v
